config/routes.rb
Rails.application.routes.draw do
root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }

  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail, message: "%{model} should be use once per cocktail"}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  # validates :name, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredient = Ingredient.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail  = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1485265449635-ca623a55e95c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80);">
  <div class="container">
    <h1>Awesome beverages to keep you cool all Summer long...and get you drunk</h1>
    <p><span id="banner-typed-text"></span></p>

    <form autocomplete="off" novalidate="novalidate" class="simple_form search mt-5 d-flex justify-content-between" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
      <div class="autocomplete search-form-control form-group flex-grow-1 mr-3">
        <input id="myInput" class="form-control string required" type="text" name="myCocktail" placeholder="Cocktail" style="opacity: 0.7">
      </div>
      <button name="button" type="submit" class="btn btn-flat" style="height: 56px;">
        <i class="fas fa-search"></i> Search
      </button>
    </form>

  </div>
</div>

<div class="cards m-4">
  <% @cocktails.each do |cocktail| %>
    <% if cocktail.photo.attached? %>

      <div class="card-category m-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, crop: :fill %>')">
        <%= link_to cocktail.name , cocktail_path(cocktail)  %>
      </div>

    <% else %>

      <div class="card-category m-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cocktail.picture %>)">
      <%= link_to cocktail.name , cocktail_path(cocktail)  %>
      </div>

    <% end %>

  <% end %>
</div>


<!-- autocomplete feature -->

<% @array = [] %>
<% Cocktail.all.each {|cocktail| @array << cocktail.name} %>

<script>
  function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        /*close any already open lists of autocompleted values*/
        closeAllLists();
        if (!val) { return false;}
        currentFocus = -1;
        /*create a DIV element that will contain the items (values):*/
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        /*append the DIV element as a child of the autocomplete container:*/
        this.parentNode.appendChild(a);
        /*for each item in the array...*/
        for (i = 0; i < arr.length; i++) {
          /*check if the item starts with the same letters as the text field value:*/
          if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
            /*create a DIV element for each matching element:*/
            b = document.createElement("DIV");
            /*make the matching letters bold:*/
            b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
            b.innerHTML += arr[i].substr(val.length);
            /*insert a input field that will hold the current array item's value:*/
            b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
            /*execute a function when someone clicks on the item value (DIV element):*/
            b.addEventListener("click", function(e) {
                /*insert the value for the autocomplete text field:*/
                inp.value = this.getElementsByTagName("input")[0].value;
                /*close the list of autocompleted values,
                (or any other open lists of autocompleted values:*/
                closeAllLists();
            });
            a.appendChild(b);
          }
        }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function(e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
          /*If the arrow DOWN key is pressed,
          increase the currentFocus variable:*/
          currentFocus++;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 38) { //up
          /*If the arrow UP key is pressed,
          decrease the currentFocus variable:*/
          currentFocus--;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 13) {
          /*If the ENTER key is pressed, prevent the form from being submitted,*/
          e.preventDefault();
          if (currentFocus > -1) {
            /*and simulate a click on the "active" item:*/
            if (x) x[currentFocus].click();
          }
        }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }
    /*execute a function when someone clicks in the document:*/
    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });
  }

  /*An array containing all the cocktail names in the world:*/
  var cocktails = <%= @array.to_json.html_safe %>;
  console.log(cocktails);
  /*initiate the autocomplete function on the "myInput" element, and pass along the cocktails array as possible autocomplete values:*/
  autocomplete(document.getElementById("myInput"), cocktails);
</script>

app/views/cocktails/new.html.erb
<div class="row justify-content-center" style="padding: 64px 100px 0px 0px">
  <div class="d-flex flex-column col-md-4">
    <div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1578553981438-cebe08c94b4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80'); background-size: cover; background-position: center; flex-grow: 1; height: 80vh;">
    </div>
  </div>
  <div class="d-flex flex-column col-md-4 col-md-8 mt-4">

    <h1 style="margin-bottom: 24px">Create a new cocktail</h1>

    <div class="gif d-flex justify-content-center">
      <img src="https://media.giphy.com/media/l3fQaE2lbSAPUnB04/giphy.gif" alt="this slowpoke moves" style="height: 250px; width: 250px; object-fit: cover; border-radius: 50%;">
    </div>

     <div class="create-form">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-flat' %>
      <% end %>
    </div>

  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container" style="border-radius: 5px; padding-top:64px">
  <div class="card-trip" >
    <% if @cocktail.photo.attached? %>

      <div class="card-trip-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')">
      <h1><%= @cocktail.name %></h1>
      </div>

    <% else %>

      <div class="card-trip-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @cocktail.picture %>)">
      <h1><%= @cocktail.name %></h1>
      </div>

    <% end %>

    <div class="card-trip-infos">
      <div>
        <h2 class="mb-4">Ingredients</h2>
        <ul class="list-group list-group-flush">
          <% @cocktail.doses.each do |dose|  %>
            <li class="list-group-item"><%= dose.description %> - <%= dose.ingredient.name %> </li>
          <% end %>
          </ul>
      </div>
      <%= link_to 'Modify receipe', new_cocktail_dose_path(@cocktail), class: 'btn btn-flat card-trip-pricing' %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container" style="border-radius: 5px; padding-top:64px">
  <div class="card-trip" >
    <% if @cocktail.photo.attached? %>

      <div class="card-trip-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')">
      <h1><%= @cocktail.name %></h1>
      </div>

    <% else %>

      <div class="card-trip-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @cocktail.picture %>)">
      <h1><%= @cocktail.name %></h1>
      </div>

    <% end %>

    <div class="card-trip-infos">
      <div>
        <h2 class="mb-4">Ingredients</h2>
        <ul class="list-group list-group-flush">
          <% @cocktail.doses.each do |dose|  %>
            <li class="list-group-item"><%= dose.description %> - <%= dose.ingredient.name %> <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          <% end %>
          </ul>
      </div>

      <div class="create-form">
        <h2 class="mb-4" style="width: 50vh">Add a new dose</h2>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient, placeholder: "vodka" %>
          <%= f.input :description, placeholder: "6 ml" %>
          <%= f.button :submit, class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%">
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" /> -->

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true%>
  </head>

  <body style="height: 100%;  display:flex; flex-direction:column ">
    <% if controller_name == "cocktails" && action_name == "index"%>
      <%= render "shared/navbarhome" %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Selected with <i class="fas fa-heart"></i> by Moumou
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="d-flex align-items-center">
    <img src="http://res.cloudinary.com/dfrtup7hb/image/upload/v1597412644/octopus_ctuwzz.png" alt="" style="width: 40px">
    <h1 class="text-white mb-0 ml-2">Moumou's bevrages</h1>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active font-weight-bold">
        <%= link_to "Home", cocktails_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "New cocktails", new_cocktail_path, class: "nav-link nav-link text-white" %>
      </li>
      <li>
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1578110927497-055e642f1ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" />
      </li>
   <!--  <li class="nav-item dropdown">
      <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1578110927497-055e642f1ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" />
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
      </div>
    </li> -->
    </ul>
  </div>
</div>

app/views/shared/_navbarhome.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home fixed-top">
  <div class="d-flex align-items-center">
    <img src="http://res.cloudinary.com/dfrtup7hb/image/upload/v1597412644/octopus_ctuwzz.png" alt="" style="width: 40px">
    <h1 class="text-white mb-0 ml-2">Moumou's bevrages</h1>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active font-weight-bold">
        <%= link_to "Home", cocktails_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "New cocktails", new_cocktail_path, class: "nav-link nav-link text-white" %>
      </li>
      <li>
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1578110927497-055e642f1ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" />
      </li>
   <!--  <li class="nav-item dropdown">
      <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1578110927497-055e642f1ff4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" />
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
      </div>
    </li> -->
    </ul>
  </div>
</div>